import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Main specification sidebar
  specSidebar: [
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'doc', 
      id: 'index',
      label: 'Specifications Overview',
    },
    // Single version specs - show as direct links
    {
      type: 'doc',
      id: 'type/0.1.0',
      label: 'Type Definition',
    },
    {
      type: 'doc',
      id: 'canon-protocol/0.1.0',
      label: 'Canon Protocol',
    },
    {
      type: 'doc',
      id: 'canon-protocol-registry/0.1.0',
      label: 'Canon Protocol Registry',
    },
    {
      type: 'doc',
      id: 'registry/0.1.0',
      label: 'Canon Registry',
    },
    // Multi-version spec - show as category
    {
      type: 'category',
      label: 'Canon Project',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'project',
        }
      ],
    },
    {
      type: 'doc',
      id: 'protocol/0.1.0',
      label: 'Canon Protocol Spec',
    },
  ],
};

export default sidebars;
